# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.console=plain
org.gradle.parallel=true
# Mod properties
mod_version=1.1.0-dev-2
maven_group=cool.muyucloud.croparia
archives_name=croparia-if
enabled_platforms=fabric,neoforge
# Minecraft
minecraft_version=1.21.1
# Tomlj
tomlj_version=1.1.1
antlr_version=4.11.1
# Parchment mapping https://parchmentmc.org/docs/getting-started
parchment_version=2024.11.17
# Dependencies
# Architectury API https://modrinth.com/mod/architectury-api/versions
architectury_api_version=13.0.8
# Fabric https://fabricmc.net/develop/
fabric_loader_version=0.18.4
fabric_api_version=0.116.7+1.21.1
# NeoForge https://neoforged.net/
neoforge_version=21.1.218
# REI https://modrinth.com/mod/rei/versions
rei_version=16.0.799
# JEI https://modrinth.com/mod/jei/versions
jei_version=19.27.0.340
# EMI not available in 1.21.4
#emi_version=1.1.18+1.21.1
# KubeJs not available in 1.21.4
#kubejs_version=2101.7.1-build.181
#rhino_version=2101.2.6-build.58