path = "croparia/ritual_${datetime}.json"
extensions = "croparia:ritual"
block = "#croparia:ritual_stands"
template = """
{
  "type": "croparia:ritual",
  "ritual": ${block},
  "ingredient": ${item},
  "block": ${ritual_input},
  "result": ${off_hand}
}
"""