registry = "croparia:crops"
path = "botanypots/recipe/${id.namespace}/crop/${id.path}.json"
dependencies = "botanypots"
template = """
{
  "type": "botanypots:crop",
  "input": {
    "item": "${seed}"
  },
  "categories": [
    "crop", "farmland"
  ],
  "growthTicks": 1200,
  "display": {
    "type": "botanypots:aging",
    "block": "${crop_block}"
  },
  "drops": [
    {
      "type": "botanypots:items",
      "items": [
        {
          "result": {
            "id": "${seed}"
          },
          "chance": 0.01
        },
        {
          "result": {
            "id": "${fruit}"
          },
          "chance": 1.00
        }
      ]
    }
  ]
}
"""