registry = "croparia:crops"
path = "c/tags/item/fruits.json"
type = "croparia:aggregated"
startup = true
content = '    "${fruit}"'
template = """
{
  "replace": false,
  "values": [
${content}
  ]
}
"""