registry = "croparia:elements"
path = "croparia/recipes/crafting/gem/${name}_from_potion.json"
template = """
{
  "type": "minecraft:crafting_shapeless",
  "category": "misc",
  "ingredients": [
    {
      "item": "${potion}"
    }
  ],
  "result": {
    "item": "${gem}"
  }
}
"""
