registry = "croparia:melons"
path = "croparia/tags/block/stem/grown.json"
type = "croparia:aggregated"
startup = true
content = '    "${attach}"'
template = """
{
  "replace": false,
  "values": [
${content}
  ]
}
"""
