registry = "croparia:elements"
path = "croparia/recipe/crafting/gem/{name}_from_bucket.json"
template = """
{
  "type": "minecraft:crafting_shapeless",
  "category": "misc",
  "ingredients": [
    "{bucket}"
  ],
  "result": {
    "id": "{gem}"
  }
}
"""