registry = "croparia:crops"
path = "croparia/recipe/crafting/material_seed/${id.namespace}/${id.path}.json"
template = """
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "item": "${seed}"
    }
  ],
  "result": {
    "id": "${material.result.id}",
    "components": ${material.result.components},
    "count": 4
  }
}
"""