registry = "croparia:crops"
path = "croparia/recipe/crafting/seeds/${id.namespace}/${id.path}.json"
template = """
{
  "type": "minecraft:crafting_shaped",
  "key": {
    "C": "${croparia}",
    "M": "${material.name}",
    "S": "#croparia:seed_ingredient"
  },
  "pattern": [
    "MSM",
    "SCS",
    "MSM"
  ],
  "result": {
    "id": "${seed}",
    "count": 1
  }
}
"""