registry = "croparia:crops"
path = "croparia/recipe/crafting/seeds/${id.namespace}/${id.path}.json"
template = """
{
  "type": "minecraft:crafting_shaped",
  "key": {
    "C": {
      "item": "${croparia}"
    },
    "M": {
      "${material.type}": "${material.name}"
    },
    "S": {
      "tag": "croparia:seed_ingredient"
    }
  },
  "pattern": [
    "MSM",
    "SCS",
    "MSM"
  ],
  "result": {
    "id": "${seed}",
    "count": 1
  }
}
"""