registry = "croparia:elements"
path = "croparia/recipe/crafting/potion/${name}.json"
template = """
{
  "type": "minecraft:crafting_shapeless",
  "category": "misc",
  "ingredients": [
    {
      "item": "${gem}"
    },
    {
      "item": "minecraft:glass_bottle"
    }
  ],
  "result": {
    "id": "${potion}"
  }
}
"""