registry = "croparia:crops"
path = "croparia/recipes/infusor/melon/material_seed/${id.namespace}/${id.path}.json"
template = """
{
  "type": "croparia:infusor",
  "element": "elemental",
  "ingredient": "${seed}",
  "result": {
    "id": "${material.result.id}",
    "nbt": ${material.result.nbt},
    "amount": 4
  }
}
"""
