registry = "croparia:melons"
path = "croparia/recipes/crafting/melon/material/${id.namespace}/${id.path}.json"
template = """
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "item": "${melon}"
    }
  ],
  "result": {
    "item": "${material.result.id}",
    "count": ${material.result.amount}
  }
}
"""
