registry = "croparia:crops"
path = "croparia/recipes/crafting/material/crop/${id.path}.json"
template = """
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "item": "${fruit}"
    }
  ],
  "result": {
    "item": "${material.result.id}",
    "count": ${material.result.amount}
  }
}
"""
