registry = "croparia:melons"
path = "croparia/tags/blocks/stem.json"
type = "croparia:aggregated"
startup = true
content = '    "${stem}"'
template = """
{
  "replace": false,
  "values": [
${content}
  ]
}
"""
