registry = "croparia:elements"
path = "gtceu/recipe/croparia/extractor/fluid/${name}.json"
dependencies = "gtceu"
template = """
{
  "type": "gtceu:extractor",
  "duration": 40,
  "inputs": {
    "item": [
      {
        "content": {
          "type": "gtceu:sized",
          "count": 1,
          "ingredient": {
            "item": "${gem}"
          }
        },
        "chance": 10000,
        "maxChance": 10000,
        "tierChanceBoost": 0
      }
    ]
  },
  "outputs": {
    "fluid": [
      {
        "content": {
          "amount": 250,
          "value": [
            {
              "fluid": "${fluid_source}"
            }
          ]
        },
        "chance": 10000,
        "maxChance": 10000,
        "tierChanceBoost": 0
      }
    ]
  },
  "tickInputs": {
    "eu": [
      {
        "content": 120,
        "chance": 10000,
        "maxChance": 10000,
        "tierChanceBoost": 0
      }
    ]
  },
  "category": "gtceu:extractor_recycling"
}
"""