registry = "croparia:elements"
path = "indrev/recipe/croparia/smelter/fluid/${name}.json"
dependencies = "indrev"
template = """
{
  "type": "indrev:smelter",
  "ingredients": {
    "item": "${gem}"
  },
  "fluidOutput": {
    "fluid": "${fluid_source}",
    "amount": 20250
  },
  "processTime": 600
}
"""