registry = "croparia:elements"
path = "indrev/recipe/croparia/condenser/gem/${name}.json"
dependencies = "indrev"
template = """
{
  "type": "indrev:condenser",
  "fluidInput": {
    "fluid": "${fluid_source}",
    "amount": 20250
  },
  "output": {
    "item": "${gem}",
    "count": 1
  },
  "processTime": 500
}
"""