registry = "croparia:elements"
path = "modern_industrialization/recipe/croparia/blast_furnace/fluid/${name}.json"
dependencies = "modern_industrialization"
template = """
{
  "type": "modern_industrialization:blast_furnace",
  "eu": 4,
  "duration": 60,
  "item_inputs": {
    "item": "${gem}",
    "amount": 1
  },
  "fluid_outputs": {
    "fluid": "${fluid_source}",
    "amount": 250
  }
}
"""