registry = "croparia:elements"
path = "thermal/recipe/croparia/crucible/fluid/${name}.json"
dependencies = "thermal_expansion"
template = """
{
  "type": "thermal:crucible",
  "ingredient": {
    "item": "${gem}"
  },
  "result": [
    {
      "fluid": "${fluid_source}",
      "amount": 250
    }
  ],
  "energy": 20000
}
"""