registry = "croparia:elements"
path = "${id.namespace}/models/block/${liquid_block.path}.json"
startup = true
template = """
{
  "textures": {
    "particle": "${id.namespace}:block/${id.path}_still"
  }
}
"""