registry = "croparia:elements"
path = "{id_namespace}/items/{potion_path}.json"
startup = true
template = """
{
  "model": {
    "type": "minecraft:model",
    "model": "{id_namespace}:item/{potion_path}"
  }
}
"""