registry = "croparia:elements"
path = "${id.namespace}/items/${gem.path}.json"
startup = true
template = """
{
  "model": {
    "type": "minecraft:model",
    "model": "${id.namespace}:item/${gem.path}"
  }
}
"""