registry = "croparia:elements"
path = "${id.namespace}/blockstates/${liquid_block.path}.json"
startup = true
template = """
{
  "variants": {
    "": {
      "model": "${id.namespace}:block/${liquid_block.path}"
    }
  }
}
"""