registry = "croparia:crops"
path = "{id_namespace}/items/{seed_path}.json"
startup = true
template = """
{
  "model": {
    "type": "minecraft:model",
    "model": "croparia:item/template_seed",
    "tints": [
      {
        "type": "minecraft:constant",
        "value": {color}
      }
    ]
  }
}
"""