registry = "croparia:elements"
path = "{id_namespace}/blockstates/{liquid_block_path}.json"
startup = true
template = """
{
  "variants": {
    "": {
      "model": "{id_namespace}:block/{liquid_block_path}"
    }
  }
}
"""