registry = "croparia:elements"
path = "${id.namespace}/models/item/${gem.path}.json"
startup = true
template = """
{
    "parent": "item/generated",
    "textures": {
        "layer0": "${id.namespace}:item/${gem.path}"
    }
}
"""