registry = "croparia:elements"
path = "${id.namespace}/items/${bucket.path}.json"
startup = true
template = """
{
  "model": {
    "type": "minecraft:model",
    "model": "croparia:item/bucket_template",
    "tints": [
      {
        "type": "minecraft:constant",
        "value": -1
      },
      {
        "type": "minecraft:constant",
        "value": ${color.dec}
      }
    ]
  }
}
"""