registry = "croparia:elements"
path = "${id.namespace}/tags/items/fluid/${id.path}.json"
startup = true
template = """
{
  "replace": false,
  "values": [
    "${fluid_source}",
    "${fluid_flowing}"
  ]
}
"""
