registry = "croparia:elements"
path = "{id_namespace}/items/{bucket_path}.json"
startup = true
template = """
{
  "model": {
    "type": "minecraft:model",
    "model": "croparia:item/bucket_template",
    "tints": [
      {
        "type": "minecraft:constant",
        "value": -1
      },
      {
        "type": "minecraft:constant",
        "value": {color}
      }
    ]
  }
}
"""