registry = "croparia:elements"
path = "${id.namespace}/models/item/${bucket.path}.json"
startup = true
template = """
{
  "parent": "item/generated",
  "textures": {
    "layer0": "croparia:item/bucket_layer",
    "layer1": "croparia:item/liquid_layer"
  }
}
"""